---
db:
  image: postgres

testoutput:
  image: busybox
  volumes:
    - /test-output
base:
  build: .
app:
  build: dockerfiles/test
  links:
   - db
  volumes:
   - duwamish_static:/duwamish/static
  volumes_from:
   - testoutput
  ports:
   - "8000:8000"
  environment:
    DJANGO_SETTINGS_MODULE: "project.settings"
    DEBUG: True
    DATABASE_URL: "postgres://postgres@db/postgres"
    SITE_URL: ""
    SITE_KEY: ""
    # UWSGI_CONFIG_TYPE: test

